BookReviewsProject/urls.py
from django.contrib import admin
from django.urls import path, include
import forum.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('books/', include('books.urls')),
    path('reviews/', include('reviews.urls')),
    path('forum/', forum.views.forum_home),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls'))

]

books/urls.py
from django.contrib import admin
from django.urls import path, include
import books.views


urlpatterns = [
    path('', books.views.index),
    path('all', books.views.show_books,
         name='all_books_route'),
    path('authors/', books.views.show_authors),
    path('create', books.views.create_book),
    path('update/<book_id>', books.views.edit_book,
         name='update_book_route'),
    path('delete/<book_id>', books.views.delete_book,
         name="delete_book_route"),
    path('authors/update/<author_id>', books.views.update_author,
         name='update_author_route'),
    path('authors/create', books.views.create_author),
    path('details/<book_id>', books.views.view_book, name="view_book_details")
]

cart/urls.py
from django.urls import path

import cart.views

urlpatterns = [
    path('add/<book_id>', cart.views.add_to_cart, name="add_to_cart"),
    path('view', cart.views.view_cart, name="view_cart"),
    path('remove/<book_id>', cart.views.remove_from_cart, name="remove_from_cart"),
    path('update_quantity/<book_id>', cart.views.update_quantity, name="update_cart_quantity")
]

books/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
# Create your models here.

from django.core.validators import MinLengthValidator


class Tag(models.Model):
    title = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.title


class Genre(models.Model):
    title = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.title


class Book(models.Model):
    title = models.CharField(blank=False, max_length=255, validators=[
                             MinLengthValidator(3)])
    ISBN = models.CharField(blank=False, max_length=255)
    desc = models.TextField(blank=False)
    pageCount = models.IntegerField(blank=False)
    # relationship to genre
    # if the genre, all the books related to the genre will be deleted as well
    # aka. cascading delete
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    authors = models.ManyToManyField('Author')
    # set the owner relationship to be NULLABLE so that it is not complusory for all books to have an owner
    # with `null=True` the relationship is optional (i.e, can be set to NULL)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    cost = models.DecimalField(max_digits=10, decimal_places=3, blank=False)
    cover = CloudinaryField()

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(blank=False, max_length=80)
    last_name = models.CharField(blank=False, max_length=80)
    dob = models.DateField(blank=False)

    def __str__(self):
        return self.first_name + " " + self.last_name


class Category(models.Model):
    title = models.CharField(blank=False, max_length=255)

    def __str__(self):
        return self.title

reviews/models.py
from django.db import models
from django.contrib.auth.models import User


# import the book model from the Reviews app
from books.models import Book

# Create your models here.


class Review(models.Model):
    title = models.CharField(max_length=255, blank=False)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    # because of the content of the review is likely to be super long
    # so we can use text field isntead of char field.
    content = models.TextField(blank=False)
    date = models.DateField(blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __str__(self):
        return self.text[0:50]

books/forms.py
from django import forms
from .models import Book, Author, Genre
from cloudinary.forms import CloudinaryJsFileField


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        # tuple are in round parenthesis
        # they are like lists in Python
        # once we put something in a tuple, we cannot change the tuple anymore
        fields = ('title', 'desc', 'ISBN', 'pageCount', 'genre', 'category',
                  'tags', 'authors', 'owner', 'cost', 'cover')
    cover = CloudinaryJsFileField()


class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = ('first_name', 'last_name', 'dob')


# SearchForm inherits from `forms.Form`, not `forms.ModelForm`
# This is because the search form doesn't have any models
# meaning it does not refer to any tables in our SQL database
class SearchForm(forms.Form):
    # the requried is `False` so that if the user leaves it blank
    # it will return all the books
    title = forms.CharField(max_length=100, required=False)

    # Genre.objects.all() is eqv to "SELECT * FROM Genre"
    # take the results of Genre.objects.all and populate the <select>
    genre = forms.ModelChoiceField(queryset=Genre.objects.all(),
                                   required=False)

    min_page_count = forms.IntegerField(required=False)

books/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Book, Author
from .forms import BookForm, AuthorForm, SearchForm

# Create your views here.
# A view (in other words, a view function) refers to a function
# that is called when its corrosponding URL is visited in the browser


# ALL view functions must take in the variable request as the first argumernt
def index(request):
    form = SearchForm(request.GET)

    if request.GET:
        # create a query that is always true
        query = ~Q(pk__in=[])  # This means TRUE
        # WHERE 1

        # if the user fills in the title and the title is not an empty string
        if 'title' in request.GET and request.GET['title']:
            title = request.GET['title']
            query = query & Q(title__icontains=title)
            # WHERE 1 and title LIKES "%{title}%"

        if 'genre' in request.GET and request.GET['genre']:
            genre_id = request.GET['genre']
            query = query & Q(genre=genre_id)

        if 'min_page_count' in request.GET and request.GET['min_page_count']:
            min_page_count = request.GET['min_page_count']
            page_query = Q(pageCount__gte=min_page_count)
            query = query & page_query

        # select all the books
        # SELECT * FROM Books
        books = Book.objects.all()

        # make sure to reassign back to the query set
        books = books.filter(query)

        return render(request, 'books/index.template.html', {
            'form': form,
            'books': books
        })
    else:
        # if the user never submit form, then just display the books:
        books = Book.objects.all()
        return render(request, 'books/index.template.html', {
            'form': form,
            'books': books
        })

    # form = SearchForm(request.GET)

    # # SELECT * FROM Books
    # # books is a QUERY SET
    # books = Book.objects.all()

    # # A query object represents a fragment of a SQL query
    # # means: WHERE title LIKE "%ring%"
    # subquery = Q(title__icontains="fire")

    # # Genre ID 1 is fantasy
    # # Genre ID  2 is science-fic
    # genre_filter = Q(genre=1)  # WHERE genre = 1

    # # books = books.filter(subquery)
    # books = books.filter(subquery)
    # # means: SELECT * FROM Books where Genre =1 AND Title LIKE "%ring%"

    # return render(request, 'books/index.template.html', {
    #     'form': form,
    #     'books': books
    # })


def show_books(request):
    # SELECT * FROM Books
    all_books = Book.objects.all()
    return render(request, 'books/all_books.template.html', {
        'books': all_books
    })


def view_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'books/details.template.html', {
        "book": book
    })


@ login_required
def create_book(request):

    # check if we are submitting the form
    if request.method == "POST":

        # create the BooKForm by filling it with data from the user's
        # submission
        form = BookForm(request.POST)

        if form.is_valid():
            # create a model based on the data in the form
            form.save()

            # the book is created
            messages.success(request, "New book has been created")

            # redirect back to the show_books view function
            return redirect(reverse(show_books))
        else:
            return render(request, 'books/create_book.template.html', {
                'form': form
            })

    else:
        # create an instance of the class BookForm and store it in the form
        # variable
        form = BookForm()
        return render(request, 'books/create_book.template.html', {
            'form': form
        })


def show_authors(request):
    all_authors = Author.objects.all()
    return render(request, 'books/all_authors.template.html', {
        'authors': all_authors
    })


def create_author(request):
    # check if has been form has been submitted with data
    # if it has been submited with data, then request.method should be "POST"
    if request.method == "POST":
        # user has submitted the data
        form = AuthorForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "New author has been created")
            return redirect(reverse(show_authors))
        else:
            return render(request, 'books/create_author.template.html', {
                'form': form
             })
    else:
        # if user has not submitted data, it's a GET request,
        # so we will just show an empty form
        form = AuthorForm()
        return render(request, 'books/create_author.template.html', {
            'form': form
        })


def update_author(request, author_id):
    # retrieve the author because we either need to update it,
    # or to show it in a form
    author = get_object_or_404(Author, pk=author_id)

    # if the user has submitted the form
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=author)
        form.save()
        return redirect(reverse(show_authors))
    else:
        # if the user didn't submit the form
        form = AuthorForm(instance=author)
        return render(request, 'books/edit_author.template.html', {
            'form': form,
            'author': author
        })


def edit_book(request, book_id):

    # retrieve the book that we want to edit
    book = get_object_or_404(Book, pk=book_id)

    # if the form is submitted, process the update
    if request.method == "POST":
        # the user has submitted data by extracting it from the request.POST
        # and passing it to the form
        form = BookForm(request.POST, instance=book)
        form.save()
        return redirect(reverse(show_books))

    else:
        # if there is no form submitted, then we display the form

        # populate the form with the existing data from the book
        form = BookForm(instance=book)
        return render(request, 'books/edit_book.template.html', {
            'form': form
        })


def delete_book(request, book_id):

    book = get_object_or_404(Book, pk=book_id)

    # if the form is submitted
    if request.method == "POST":
        book.delete()
        return redirect(reverse(show_books))
    else:
        # if no form is submitted (that is, just to see the confirmation)
        return render(request, 'books/confirm_delete_book.template.html', {
            'book': book
        })

books/templates/books/all_authors.template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {%for author in authors %}
            <li>{{author.first_name}} {{author.last_name}}
                <a href="{% url 'update_author_route' author_id=author.id %}">Edit</a>
            </li>
        {%endfor%}
    </ul>
</body>
</html>

books/templates/books/all_books.template.html
{% extends 'base.template.html' %}

{%block content%}
    <h1>All the Books</h1>
    <ul>
        {%for book in books %}
        <li>
            <a href="{% url 'view_book_details' book_id=book.id %}">
            {{book.title}}
            </a>
                            
            <a class="btn btn-primary btn-sm" href="{% url 'update_book_route' book_id=book.id %}">Edit</a>
            <a class="btn btn-primary btn-sm" href="{% url 'delete_book_route' book_id=book.id %}">Delete</a>
            <a class="btn btn-primary btn-sm" href="{% url 'add_to_cart' book_id=book.id%}">Add to Cart</a>
        </li>
        {%endfor%}
    </ul>
{%endblock%}

books/templates/books/confirm_delete_book.template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Deleting book {{book.title}}</h1>
    <p>Are you sure</p>
    <form method="POST">
        {% csrf_token %}
        <input type="submit" value="Yes"/>
        <a href="{% url 'all_books_route'%}">Cancel</a>
    </form>
</body>
</html>

books/templates/books/create_author.template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Create an author</h1>
    <form method="POST"> 
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create Author"/>
    </form>
</body>
</html>

books/templates/books/create_book.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}
{% load static %}

{%block content %}
    <form method="POST" enctype="multipart/form-data" id="form">
	{%csrf_token%}
	{{form|crispy}}
	<input type="submit"/>
    </form>

	<div class="status">
		<h2>Status</h2>
		<span class="status_value">Idle</span>
	</div>

	<div class="uploaded_info_holder">

	</div>
{%endblock%}

{%block js %}
	{% cloudinary_includes %}
	{% cloudinary_js_config %}
	<script>
		function prettydump(obj) {
            ret = ""
            $.each(obj, function(key, value) {
            ret += "<tr><td>" + key + "</td><td>" + value + "</td></tr>";
            });
            return ret;
        }

        // jQuery ready
        $(function(){
            // console.log("Hello");
            $("#form input[type='file']").cloudinary_fileupload({
                dropZone:"#form",
                start: function() {
                    console.log("Starting upload...")
                    $('.status_value').text("Starting direct upload...")
                },
                progress:function() {
                    console.log("uploading...")
                    $('.status_value').text("Uploading...");
                }
            }).on("cloudinarydone", function(e, data){
               $('.status_value').text("Upload done");

               // for debugging
                var info = $('<div class="uploaded_info"/>');
                        $(info).append($('<div class="data"/>').append(prettydump(data.result)));
                        $(info).append($('<div class="image"/>').append(
                        $.cloudinary.image(data.result.public_id, {
                        format: data.result.format, width: 150, height: 150, crop: "fill"
                    })
                ));
                $('.uploaded_info_holder').append(info);
                // end debugging         
                // $("#div_id_cover").remove()
                $("#form input[type='file']").parent().parent().remove();
            })  

            
        }) // end $(function
    </script>

{%endblock%}

books/templates/books/details.template.html
{% extends 'base.template.html' %}
{% load cloudinary %}
{%block content %}
<div class="card">
    <div class="card-body">
        <div class="card-title"><h1>{{book.title}}</h1></div>

        {% cloudinary book.cover %}

        <h2>Authors</h2>
        <ul>
            {%for a in book.authors.all %}
                <li>{{a.first_name}} {{a.last_name}}</li>
            {%endfor%}
        </ul>

        <h2>Tags</h2>
      
       {%for t in book.tags.all %}
            <span class="badge badge-pill badge-primary">{{t.title}}</span>
       {%endfor%}
       
       <div class="mt-3"> 
            <a href="{% url 'create_review_route' book_id=book.id %}" class="btn btn-primary btn-sm">Add a review</a>   
       </div>
    </div>
</div>

<!-- show all the reviews -->
<h1>Reviews</h1>
{% for r in book.review_set.all %}
<div class="card">
    <div class="card-body">
        <div class="card-title">
            <h2>{{r.title}}</h2>
        </div>
        <div>
            {{r.content}}
        </div>

        <p>By {{ r.user.username}}</p>    
        <a href="{% url 'create_comment_route' review_id=r.id%}" class="btn btn-primary btn-sm">Leave a comment</a>
    </div>
</div>
{% endfor%}
{%endblock%}

books/templates/books/edit_author.template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Editing {{author.first_name}} {{author.last_name}}</h1>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update">
    </form>
</body>
</html>

books/templates/books/edit_book.template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Edit book: {{book.title}} </h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="Update Book"/>
    </form>
</body>
</html>

books/templates/books/index.template.html
{% extends 'base.template.html' %}
{% load crispy_forms_tags %}
{%load static %}

{%block title%}All Books{%endblock%}

{%block content %}
    {% if request.user.is_authenticated %}
    <h1>Welcome, {{request.user}}</h1>
    {% endif %}

    <form method="GET">
        {{form|crispy}}
        <input type="submit" value="Search"/>
    </form>

    <h2 class="mt-5">Books Found</h2>
    <ul>
    {%for b in books %}
        <li>{{b.title}} ({{b.genre.title}}), number of pages = {{b.pageCount}}</li>
    {%endfor%}
    </ul>

{%endblock%}